name: Build and push docker Image

on:
  push:
    branches:
      - master

jobs:
  Docker-Build-push:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v6
      # - uses: actions/setup-java@v5
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'
      #     cache: 'maven'
      - name: Build Project
        run: mvn --version